### ISSUE TITLE
Change Sign In and Sign Out HTTP Status Codes

### ISSUE THREAD

**Issue by Thinbishop** [chrispinkney/cinesync#26]
The `/signin` and `/signout` endpoints use `POST` requests to sign the user in and out, respectively. Nest JS defaults any `POST` request to `201 - Created`, however during a sign-in and sign-out, there is no content created on the api server, so the codes should be changed. This can be done using the [`@HttpCode(...)` decorator](https://docs.nestjs.com/controllers#status-code) in the user controller.

The new codes should be as follows:

- Sign In: `200: OK`
- Sign Out `204: No Content`

**Comment by deimosOmegaChan** [comment]
Please assign this to me
