### ISSUE TITLE
Implement responsive design for all of frontend

### ISSUE THREAD

**Issue by chrispinkney** [chrispinkney/cinesync#54]
Currently on mobile the sidebar takes up the entire page. A lot of the app will need rejigging but having a true responsive design is required since most people do their browsing on mobile these days.

**Comment by Thinbishop** [comment]
The movie list table needs to be responsive as well:
- Table/column width (could be horizontallly scrollable)
- row height (genres/descriptions overflowing)

**Comment by chrispinkney** [comment]
As per our discussion I think it'd be good to remove the sidebar since it doesn't serve a purpose plus the home page. Also see #116.

**Comment by pyvelkov** [comment]
note to self:
relocate about page and friends page to avatar drop down menu.
change lists to be home page '/'
see @chrispinkney comment above #116
