### ISSUE TITLE
Implement Header

### ISSUE THREAD

**Issue by chrispinkney** [chrispinkney/cinesync#8]
The front-end needs a header which can display the following information:

- Sign-up
    - SIgn-in / Sign-out
- User Information
- Logo
- About page

The frontend should be available on every page (see [layout.tsx](https://github.com/chrispinkney/cinesync/blob/main/web/src/app/layout.tsx))

**Comment by Thinbishop** [comment]
Added component, needs full implementation of functionality

**Comment by chrispinkney** [comment]
I think most of what was required in this issue was actually solved via #22, and what remains can be handled #2.
